### PR TITLE
Add sql functions

### PR DESCRIPTION
**Pull request by AlexanderInHUST**
I've written these sql functions and modified the Go files (may cause some bugs in Go files because I didn't test Go files).
* Run the bash scripts at 
         /api/sql/load_functions.sh 
to load all functions to the database.

### CODE REVIEW

**Comment by AlexanderInHUST** [comment]
And in the original file, crypt(_password, gen_salt('bf', 8)) is not correct. Because the salt we got here is generated randomly, we cannot have the same salt to hash the input password while login to check its correctness. I change it to a simple text 'salt' temporarily and I think we should store the unique salt in database for each user.

**Comment by li-kai** [comment]
No the salt is unique to each user, and bcrypt will use the password to check the hash during validation.

**Comment by li-kai** [comment]
Could you use store procedures instead? I think we'll be marked down if we used manual iteration rather than using sql clauses.

**Comment by AlexanderInHUST** [comment]
OK... I'm sorry I know little about this pgcrypto.. I've fixed it.
But I don't understand your second comment. Maybe I misunderstand what is called store procedures, but I think I'm using it -- I put all details as postgresSQL functions and call them... Maybe you can show me where is the manual iteration that we can using sql clauses instead?

**Comment by li-kai** [comment]
Oops, I meant prepared statements 😅 , since prepared statements don't have to always return a value.

**Comment by AlexanderInHUST** [comment]
Ok😂

**Comment by AlexanderInHUST** [comment]
I read a lot about stored procedures in postgresql.
1. Some one said that postgresql doesn't support true stored procedures. It always requires sql-callable user-defined functions to implement stored procedures.
https://stackoverflow.com/questions/18315633/calling-functions-with-exec-instead-of-select
http://www.sqlines.com/postgresql/stored_procedures_functions
2. Although it still supports prepared statement, it looks kind of superfluous while we're using stored functions.
https://stackoverflow.com/questions/12707417/using-prepared-statement-in-stored-function
3. Since the lifetime of prepared statements is only one sql-session, it seems that we have to load all prepared statements when connect to the database. (is it true?) From my experience, I cannot load it in a sql file and execute it in an another one.
Maybe we can just stop move on. And I'll add more functions and triggers in the future.

**Pull request merged**
